### Listar productos
GET http://localhost:3000/api/products

### Obtener producto por ID
GET http://localhost:3000/api/products/68b5a9cc91d232abe4450749

### Crear producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Termo",
  "description": "Termo de acero inoxidable",
  "price": 35
}

### Actualizar producto
PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
  "price": 50
}

### Eliminar producto
DELETE http://localhost:3000/api/products/1
